package com.company.opsagent.contracts.events;

/**
 * 公开给操作台的 Agent 运行时进度分类。
 *
 * <p>该枚举是平台稳定语义，不等同于 AgentScope SDK 原始事件类型。
 */
public enum AgentRuntimeProgressPayloadKind {
  AGENT_STARTED,
  AGENT_ENDED,
  AGENT_RESULT_READY,
  MODEL_CALL_STARTED,
  MODEL_CALL_COMPLETED,
  TEXT_DELTA_AVAILABLE,
  TOOL_CALL_STARTED,
  TOOL_CALL_DELTA_AVAILABLE,
  TOOL_CALL_COMPLETED,
  TOOL_RESULT_STARTED,
  TOOL_RESULT_DELTA_AVAILABLE,
  TOOL_RESULT_COMPLETED,
  SUBAGENT_EXPOSED,
  ITERATION_LIMIT_EXCEEDED,
  USER_CONFIRMATION_REQUIRED,
  EXTERNAL_EXECUTION_REQUIRED,
  CUSTOM,
  UNKNOWN
}
