package com.company.opsagent.controlplane.modules.agentruntime;

/**
 * AgentScope SDK event 的平台内部进度分类。
 */
public enum AgentRuntimeProgressKind {
  AGENT_STARTED,
  AGENT_ENDED,
  AGENT_RESULT_READY,
  MODEL_CALL_STARTED,
  MODEL_CALL_COMPLETED,
  TEXT_DELTA_AVAILABLE,
  TOOL_CALL_STARTED,
  TOOL_CALL_DELTA_AVAILABLE,
  TOOL_CALL_COMPLETED,
  TOOL_RESULT_STARTED,
  TOOL_RESULT_DELTA_AVAILABLE,
  TOOL_RESULT_COMPLETED,
  SUBAGENT_EXPOSED,
  ITERATION_LIMIT_EXCEEDED,
  USER_CONFIRMATION_REQUIRED,
  EXTERNAL_EXECUTION_REQUIRED,
  CUSTOM,
  UNKNOWN
}
