package com.company.opsagent.controlplane.modules.release;

public enum ReleaseEventType {
  RELEASE_CREATED,
  RELEASE_CONFIRMED,
  RELEASE_NODE_STARTED,
  RELEASE_NODE_COMPLETED,
  RELEASE_NODE_FAILED,
  RELEASE_PARTIAL_FAILED,
  RELEASE_ROLLBACK_STARTED,
  RELEASE_ROLLBACK_FAILED,
  RELEASE_MANUAL_INTERVENTION_REQUIRED
}
